Add Student Repository and services
sysbeams/codelearnersmanagmentapp pull request #6
Opened 2024-05-22 16:07 UTC by lawsontechnology

2024-05-23 16:31 UTC, yusufadeyemi commented on Application/Contracts/Services/IStudentService.cs
> +    StudentResponse GetStudentBy(string mail);
public Task<RegisterStudentReponse> RegisterStudent(...);

2024-05-25 12:34 UTC, yusufadeyemi requested changes

2024-05-25 12:34 UTC, yusufadeyemi commented on Application/Contracts/Services/IStudentService.cs
> +        Task<GetAllStudentResponse> GetAllStudents();
Instead of GetAllStudents() simply use GetStudents(). Furthermore, GetStudents should be paginated with sorting options.

2024-05-25 12:34 UTC, yusufadeyemi commented on Application/Dtos/CreateStudentResponse.cs
> +public record CreateStudentResponse(
The create student response should extend from the BaseResponse

2024-05-25 12:34 UTC, yusufadeyemi commented on Application/Dtos/GetAllStudentResponse.cs
> +public class GetAllStudentResponse(string Message, bool IsSuccessful, IEnumerable<CreateStudentResponse> Data)
why class instead of record?

2024-05-25 12:34 UTC, yusufadeyemi commented on Application/Dtos/GetStudentResponse.cs
> +public class GetStudentResponse(string message, bool isSuccessful, CreateStudentResponse Data) : BaseResponse(message, isSuccessful);
why class instead of record

2024-05-25 12:34 UTC, yusufadeyemi commented on Application/Dtos/BaseResponse.cs
> +    public abstract class BaseResponse
this should be record

2024-05-25 16:20 UTC, yusufadeyemi approved these changes

2024-05-25 16:20 UTC, YusuffAhmad approved these changes

2024-05-25 16:21 UTC, merged